# Generated by Django 4.2.7 on 2025-09-08 02:10

from django.db import migrations, models
import django.db.models.deletion
from ..models.Roles import Roles

def load_roles(apps, schema_editor):
    rol = Roles(description='Operador logístico')
    rol.save()

    rol = Roles(description='Pasajero')
    rol.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=250)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.RunPython(load_roles),
    ]
