# Generated by Django 4.2.7 on 2025-09-08 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stops', '0001_create_table_stops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weekday', models.IntegerField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routes')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.stops')),
            ],
            options={
                'db_table': 'schedules',
            },
        ),
    ]
