# Generated by Django 4.2.7 on 2025-09-08 01:54

from django.db import migrations, models
from ..models.Cities import Cities

def load_cities(apps, schema_editor):
    city = Cities(description='Bogota')
    city.save()

    city = Cities(description='Medellin')
    city.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.RunPython(load_cities),
    ]
